# Generated by Django 3.2.11 on 2022-01-16 12:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank',
            new_name='Account',
        ),
    ]
